### ISSUE TITLE
Reorg

### ISSUE THREAD

**Issue by m-clark** [m-clark/book-of-models#33]
The following only covers reorganization, not outright trimming

**PART I**
- [x] Move all the shap and related discussion to model exploration
- [x] Move model list in LM chapter to last chapter, but leave a bit of a preview to 'other models' (this acutally wasn't that much content and was exclusively 'linear models', so left). Reminder to add others added to misc_models.
- [x] Should assumptions stay in LM or be moved to knowing? (leaving for now)
- [x] Move interactions to 'extensions' chapter, which might be renamed something to reflect nonlinear nature of the models covered there
- [x] move metrics table and other discussion from ML to model explore
- [x] in the knowing chap, talk about feature importance for other models with brief demo in model exploration (e.g. can demo RF/boost), but leave bulk of discussion to ML coverage
- [x] Update the knowing chapter to handle all the new content and rename from model_criticism.qmd

**PART II**
- [x] Trim content that appears to get too deep, duplicates content elsewhere, or otherwise just isn't necessary
   - [x] Preface 
   - [x] Intro
   - [x] Linear Models
   - [x] Knowing
   - [x] Estimation
   - [x] GLM
   - [x] Nonlin
   - [x] ML concepts
   - [x] ML models
   - [x] ML more
 
**PART III**
  - [x] Data
  - [x] Causal
  - [x] Danger Zone
  - [x] Finish last chapter (currently 'misc models')

**Other Parts**
- [x] Update Preface
- [x] Update Appendix   

**More stuff**
- [x] Put exercises for appropriate chaps
- [x] update glm per #59 
- [x] Recheck text where gaps are left and text is added so that it makes sense.
  - [x] lm chapter
  - [x] ml intro
  - [x] model exploration
  - [x] final chap
- [ ] Glossary of Models

**Comment by m-clark** [comment]
The glossary of models will likely be a web-only thing, and everything else is done on this checklist. Will create a separate issue for it.
